project:
  type: book
  output-dir: _book

book:
  title: "Janqua"
  subtitle: "Jank code in Quarto documents"
  repo-url: https://github.com/scicloj/janqua
  repo-actions: [issue]
  chapters:
    - index.qmd
    - getting-started.qmd
    - workflow.qmd
    - kindly-kinds.qmd
    - authoring.qmd
    - how-it-works.qmd
    - demo.qmd

format:
  html:
    theme: cosmo
